services:
  ardupilot-sitl:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - ARDUPILOT_CLONE_BRANCH
    env_file: docker/docker.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logs:/gps-attack/logs
    stdin_open: true
    tty: true
